server:
  port: 9999
spring:
  jackson:
    default-property-inclusion: non_null
    deserialization.fail-on-unknown-properties: false
    generator.ignore-unknown: true
  datasource:
    url: jdbc:mysql://192.168.1.86:3306/tests?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      hibernate: DEBUG